baseURL: "https://danielhons.de"
defaultContentLanguage: de
languages:
  de:
    title: "Daniel Hons - Software für höchste Ansprüche"
    LanguageName: DE
    weight: 1
  en:
    title: "Daniel Hons - First Class Software"
    LanguageName: EN
    weight: 2
disableLanguages:
  - en
theme: "dh-de"
publishDir: "docs"
enableRobotsTXT: true
paginate: 4

taxonomies:
  technology: technologien

params:
  nameWithTitle: "Dipl. math. Daniel Hons"
  company:
    name: "Algorise Solutions GmbH"
    address1: Mühlenweg 40
    address2: 54597 Pronsfeld
    register: Amtsgericht Wittlich / HRB 46854
    owner: Daniel Hons
  description: "IT mit Leidenschaft"
  email: "mail@danielhons.de"
  phone: "+49 (0) 176 62 807 613"
  taxNumber: "DE366549404"
  avatar: "images/guy.jpg"
  background: ""
  DateForm: "02. Jan 2006"
  favicon: favicon.ico
  markExternalLinks: true
  contactFormEndpoint: "https://lw6tvub74g.execute-api.eu-central-1.amazonaws.com/production/contact-form"

menu:
    main:
        - identifier: home
          name: "Home"
          pre: <i class='fa fa-heart'></i>
          url: /
          weight: -110
        - name: "Service"
          url: "/service/"
          weight: 4
        - name: "Projekte"
          url: "/projekte/"
          weight: 5
        - name: "Blog"
          url: "/post/"
          weight: 9
